//
// Copyright(C) 2026 Derek Quenneville
//
// You can redistribute and/or modify this program under the terms of the
// GNU General Public License version 2 as published by the Free Software
// Foundation, or any later version. This program is distributed WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.
//

#include "lp_video.h"
#include "text.h"

// Generated by tools/mkfont.py: LPC_FONT_H uint16 rows per glyph, the
// leftmost pixel of the cell in bit (LPC_FONT_CELL_W - 1).
#include "font_homevideo.h"

_Static_assert(LPC_FONT_CELL_W == LPC_TEXT_ADVANCE, "text.h advance");
_Static_assert(LPC_FONT_H == LPC_TEXT_HEIGHT, "text.h height");

int LPC_TextWidth(const char *s, int scale)
{
	int n = 0;

	while (s[n])
		++n;
	return n * LPC_FONT_CELL_W * scale;
}

static void Glyph(uint8_t *fb, int x, int y, unsigned ch, uint8_t colour,
                  int scale)
{
	const uint16_t *rows;
	int r, c, sy, sx;

	if (ch < LPC_FONT_FIRST || ch > LPC_FONT_LAST)
		return;
	rows = &lpc_font[(ch - LPC_FONT_FIRST) * LPC_FONT_H];

	for (r = 0; r < LPC_FONT_H; ++r) {
		if (!rows[r])
			continue;
		for (c = 0; c < LPC_FONT_CELL_W; ++c) {
			if (!(rows[r] & (1u << (LPC_FONT_CELL_W - 1 - c))))
				continue;
			for (sy = 0; sy < scale; ++sy) {
				int py = y + r * scale + sy;

				if (py < 0 || py >= LP_FB_H)
					continue;
				for (sx = 0; sx < scale; ++sx) {
					int px = x + c * scale + sx;

					if (px >= 0 && px < LP_FB_W)
						fb[py * LP_FB_W + px] = colour;
				}
			}
		}
	}
}

void LPC_TextDraw(int x, int y, const char *s, uint8_t colour, int scale)
{
	uint8_t *fb = LP_Fb();

	for (; *s; ++s, x += LPC_FONT_CELL_W * scale)
		Glyph(fb, x, y, (unsigned char) *s, colour, scale);
	LP_FbChanged();
}

void LPC_TextDrawCentred(int y, const char *s, uint8_t colour, int scale)
{
	LPC_TextDraw((LP_FB_W - LPC_TextWidth(s, scale)) / 2, y, s, colour, scale);
}
