//
// Copyright(C) 2026 Derek Quenneville
//
// You can redistribute and/or modify this program under the terms of the
// GNU General Public License version 2 as published by the Free Software
// Foundation, or any later version. This program is distributed WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.
//

#include "lp_video.h"
#include "text.h"

// Generated by tools/mkfont.py: _H uint16 rows per glyph, the leftmost pixel
// of the cell in bit (_CELL_W - 1).
#include "font_homevideo.h"
#include "font_publicpixel.h"

_Static_assert(LPC_HV_CELL_W == LPC_LARGE_ADVANCE, "text.h large advance");
_Static_assert(LPC_HV_H == LPC_LARGE_HEIGHT, "text.h large height");
_Static_assert(LPC_PP_CELL_W == LPC_SMALL_ADVANCE, "text.h small advance");
_Static_assert(LPC_PP_H == LPC_SMALL_HEIGHT, "text.h small height");

struct font {
	const uint16_t *rows;
	int cell_w;
	int h;
};

static const struct font fonts[] = {
	[LPC_FONT_LARGE] = { lpc_hv_rows, LPC_HV_CELL_W, LPC_HV_H },
	[LPC_FONT_SMALL] = { lpc_pp_rows, LPC_PP_CELL_W, LPC_PP_H },
};

_Static_assert(LPC_HV_FIRST == LPC_PP_FIRST && LPC_HV_LAST == LPC_PP_LAST,
               "both fonts cover the same range");
#define FIRST LPC_HV_FIRST
#define LAST  LPC_HV_LAST

// The pen advance for `ch`, given the character before it.
static int Advance(const struct font *f, char prev, char ch)
{
	return (ch == ' ' && prev == ':') ? f->cell_w / 2 : f->cell_w;
}

int LPC_TextWidth(enum lpc_font font, const char *s)
{
	const struct font *f = &fonts[font];
	char prev = 0;
	int w = 0;

	for (; *s; prev = *s++)
		w += Advance(f, prev, *s);
	return w;
}

static void Glyph(uint8_t *fb, const struct font *f, int x, int y, unsigned ch,
                  uint8_t colour)
{
	const uint16_t *rows;
	int r, c;

	if (ch < FIRST || ch > LAST)
		return;
	rows = &f->rows[(ch - FIRST) * (unsigned) f->h];

	for (r = 0; r < f->h; ++r) {
		int py = y + r;

		if (!rows[r] || py < 0 || py >= LP_FB_H)
			continue;
		for (c = 0; c < f->cell_w; ++c) {
			int px = x + c;

			if ((rows[r] & (1u << (f->cell_w - 1 - c))) &&
			    px >= 0 && px < LP_FB_W)
				fb[py * LP_FB_W + px] = colour;
		}
	}
}

void LPC_TextDraw(enum lpc_font font, int x, int y, const char *s, uint8_t colour)
{
	const struct font *f = &fonts[font];
	uint8_t *fb = LP_Fb();
	char prev = 0;

	for (; *s; prev = *s++) {
		Glyph(fb, f, x, y, (unsigned char) *s, colour);
		x += Advance(f, prev, *s);
	}
	LP_FbChanged();
}

void LPC_TextDrawCentred(enum lpc_font font, int y, const char *s, uint8_t colour)
{
	LPC_TextDraw(font, (LP_FB_W - LPC_TextWidth(font, s)) / 2, y, s, colour);
}
