#!/usr/bin/env python3
#
# Copyright (C) 2026 Derek Quenneville
#
# Licensed under the GNU General Public License, version 2 or later; see
# COPYING.md.
#
# Generate src/font_homevideo.h from Home Video Font by GGBotNet (CC0 1.0;
# https://ggbot.itch.io/home-video-font, see assets/font/home-video/).
#
# Home Video is a pixel font drawn on a 1 px grid at 20 px: rendered at that
# size without antialiasing every glyph is exact, 10x14 of ink inside a
# monospaced 12 px cell. The generated table is committed, so the cartridge
# build needs neither Pillow nor FreeType; run this again only if the font or
# the table layout changes. --check verifies the committed table is current.
#
# Output: LPC_FONT_H uint16 rows per glyph, ASCII 32..126, the leftmost pixel
# of the cell in bit (LPC_FONT_CELL_W - 1).
#
# Usage: python tools/mkfont.py [--check]

import argparse
import os
import sys

from PIL import Image, ImageDraw, ImageFont

CART = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TTF = os.path.join(CART, "assets", "font", "home-video", "HomeVideo-Regular.ttf")
OUT = os.path.join(CART, "src", "font_homevideo.h")

SIZE = 20       # the font's native pixel size
CELL_W = 12     # monospaced advance
TOP = 2         # first inked row below the draw origin, over all glyphs
ROWS = 14       # inked rows, over all glyphs
FIRST = 32
LAST = 126


def glyph_rows(font, ch):
    im = Image.new("1", (CELL_W * 3, SIZE * 2), 0)
    d = ImageDraw.Draw(im)
    d.fontmode = "1"
    d.text((CELL_W, 0), ch, font=font, fill=1)
    px = im.load()

    for y in range(im.height):
        for x in range(im.width):
            inside = CELL_W <= x < 2 * CELL_W and TOP <= y < TOP + ROWS
            if px[x, y] and not inside:
                sys.exit(f"glyph 0x{ord(ch):02X} has ink outside its cell "
                         f"at ({x - CELL_W}, {y})")

    rows = []
    for y in range(TOP, TOP + ROWS):
        value = 0
        for x in range(CELL_W):
            if px[CELL_W + x, y]:
                value |= 1 << (CELL_W - 1 - x)
        rows.append(value)
    return rows


def generate():
    font = ImageFont.truetype(TTF, SIZE)
    advances = {font.getlength(chr(c)) for c in range(FIRST, LAST + 1)}
    if advances != {float(CELL_W)}:
        sys.exit(f"expected a monospaced {CELL_W} px advance, got {sorted(advances)}")

    lines = [
        "// GENERATED by tools/mkfont.py from assets/font/home-video/HomeVideo-Regular.ttf.",
        "// Do not edit. Home Video Font by GGBotNet is CC0 1.0 (assets/font/home-video/License.txt).",
        "",
        "#include <stdint.h>",
        "",
        f"#define LPC_FONT_CELL_W {CELL_W}",
        f"#define LPC_FONT_H {ROWS}",
        f"#define LPC_FONT_FIRST {FIRST}",
        f"#define LPC_FONT_LAST {LAST}",
        "",
        "static const uint16_t lpc_font[] = {",
    ]
    for code in range(FIRST, LAST + 1):
        rows = glyph_rows(font, chr(code))
        values = ", ".join(f"0x{r:03X}" for r in rows)
        lines.append(f"\t{values}, /* 0x{code:02X} */")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed table is out of date")
    args = ap.parse_args()

    text = generate()
    if args.check:
        with open(OUT, encoding="ascii", newline="") as f:
            if f.read() != text:
                sys.exit(f"{OUT} is out of date; run tools/mkfont.py")
        print("font table is current")
        return

    with open(OUT, "w", encoding="ascii", newline="\n") as f:
        f.write(text)
    print(f"wrote {OUT}: {LAST - FIRST + 1} glyphs, {CELL_W}x{ROWS} cells")


if __name__ == "__main__":
    main()
