#!/usr/bin/env python3
#
# Copyright (C) 2026 Derek Quenneville
#
# Licensed under the GNU General Public License, version 2 or later; see
# COPYING.md.
#
# Generate the cart's font tables from the two pixel fonts by GGBotNet, both
# CC0 1.0:
#
#   src/font_homevideo.h    Home Video Font   https://ggbot.itch.io/home-video-font
#   src/font_publicpixel.h  Public Pixel Font https://ggbot.itch.io/public-pixel-font
#
# Both are drawn on a 1 px grid at their native size: rendered there without
# antialiasing every glyph is exact and monospaced. The tables are committed,
# so the cartridge build needs neither Pillow nor FreeType; run this again only
# if a font or the table layout changes. --check verifies the committed tables.
#
# Output per font: <PREFIX>_H uint16 rows per glyph, ASCII 32..126, the
# leftmost pixel of the cell in bit (<PREFIX>_CELL_W - 1).
#
# Usage: python tools/mkfont.py [--check]

import argparse
import os
import sys

from PIL import Image, ImageDraw, ImageFont

CART = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

FIRST = 32
LAST = 126

FONTS = [
    {
        "out": "font_homevideo.h",
        "prefix": "LPC_HV",
        "array": "lpc_hv_rows",
        "ttf": ("home-video", "HomeVideo-Regular.ttf"),
        "name": "Home Video Font",
        "url": "https://ggbot.itch.io/home-video-font",
        "size": 20,     # native pixel size
        "cell_w": 12,   # monospaced advance
        "top": 2,       # first inked row below the draw origin, over all glyphs
        "rows": 14,     # inked rows, over all glyphs
    },
    {
        "out": "font_publicpixel.h",
        "prefix": "LPC_PP",
        "array": "lpc_pp_rows",
        "ttf": ("public-pixel", "PublicPixel.ttf"),
        "name": "Public Pixel Font",
        "url": "https://ggbot.itch.io/public-pixel-font",
        "size": 8,
        "cell_w": 8,
        "top": 1,
        "rows": 7,
    },
]


def glyph_rows(font, spec, ch):
    cell_w, top, rows, size = spec["cell_w"], spec["top"], spec["rows"], spec["size"]
    im = Image.new("1", (cell_w * 3, size * 2), 0)
    d = ImageDraw.Draw(im)
    d.fontmode = "1"
    d.text((cell_w, 0), ch, font=font, fill=1)
    px = im.load()

    for y in range(im.height):
        for x in range(im.width):
            inside = cell_w <= x < 2 * cell_w and top <= y < top + rows
            if px[x, y] and not inside:
                sys.exit(f"{spec['name']}: glyph 0x{ord(ch):02X} has ink outside its "
                         f"cell at ({x - cell_w}, {y})")

    out = []
    for y in range(top, top + rows):
        value = 0
        for x in range(cell_w):
            if px[cell_w + x, y]:
                value |= 1 << (cell_w - 1 - x)
        out.append(value)
    return out


def generate(spec):
    ttf_rel = "/".join(("assets", "font") + spec["ttf"])
    font = ImageFont.truetype(os.path.join(CART, *ttf_rel.split("/")), spec["size"])
    advances = {font.getlength(chr(c)) for c in range(FIRST, LAST + 1)}
    if advances != {float(spec["cell_w"])}:
        sys.exit(f"{spec['name']}: expected a monospaced {spec['cell_w']} px advance, "
                 f"got {sorted(advances)}")

    p = spec["prefix"]
    lines = [
        f"// GENERATED by tools/mkfont.py from {ttf_rel}.",
        f"// Do not edit. {spec['name']} by GGBotNet is CC0 1.0 ({spec['url']}).",
        "",
        "#include <stdint.h>",
        "",
        f"#define {p}_CELL_W {spec['cell_w']}",
        f"#define {p}_H {spec['rows']}",
        f"#define {p}_FIRST {FIRST}",
        f"#define {p}_LAST {LAST}",
        "",
        f"static const uint16_t {spec['array']}[] = {{",
    ]
    for code in range(FIRST, LAST + 1):
        values = ", ".join(f"0x{r:03X}" for r in glyph_rows(font, spec, chr(code)))
        lines.append(f"\t{values}, /* 0x{code:02X} */")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if a committed table is out of date")
    args = ap.parse_args()

    for spec in FONTS:
        path = os.path.join(CART, "src", spec["out"])
        text = generate(spec)
        if args.check:
            with open(path, encoding="ascii", newline="") as f:
                if f.read() != text:
                    sys.exit(f"{path} is out of date; run tools/mkfont.py")
            print(f"{spec['out']} is current")
        else:
            with open(path, "w", encoding="ascii", newline="\n") as f:
                f.write(text)
            print(f"wrote {path}: {LAST - FIRST + 1} glyphs, "
                  f"{spec['cell_w']}x{spec['rows']} cells")


if __name__ == "__main__":
    main()
