#!/usr/bin/env python3
#
# Copyright (C) 2026 Derek Quenneville
#
# Licensed under the GNU General Public License, version 2 or later; see
# COPYING.md.
#
# Generate web/src/core/fonts.gen.ts: glyph tables for the two pixel fonts by
# GGBotNet (both CC0 1.0), rasterised here once so the web app draws grid-page
# text deterministically, without a canvas or FreeType at runtime.
#
#   Home Video Font    https://ggbot.itch.io/home-video-font
#   Public Pixel Font  https://ggbot.itch.io/public-pixel-font
#
# The metrics match cart/tools/lpcimage.py, whose text the TypeScript renderer
# must reproduce pixel for pixel (web/test/text.test.ts checks it).
#
# Usage: python cart/tools/mkwebfonts.py [--check]

import argparse
import os
import sys

from PIL import Image, ImageDraw, ImageFont

CART = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(CART)
OUT = os.path.join(REPO, "web", "src", "core", "fonts.gen.ts")

FIRST, LAST = 32, 126

FONTS = [
    ("HOME_VIDEO", "Home Video Font", "https://ggbot.itch.io/home-video-font",
     ("home-video", "HomeVideo-Regular.ttf"), 20, 12, 2, 14),
    ("PUBLIC_PIXEL", "Public Pixel Font", "https://ggbot.itch.io/public-pixel-font",
     ("public-pixel", "PublicPixel.ttf"), 8, 8, 1, 7),
]


def glyph_rows(font, size, cell_w, top, rows, ch, name):
    im = Image.new("1", (cell_w * 3, size * 2), 0)
    d = ImageDraw.Draw(im)
    d.fontmode = "1"
    d.text((cell_w, 0), ch, font=font, fill=1)
    px = im.load()
    for y in range(im.height):
        for x in range(im.width):
            if px[x, y] and not (cell_w <= x < 2 * cell_w and top <= y < top + rows):
                sys.exit(f"{name}: glyph 0x{ord(ch):02X} has ink outside its cell")
    out = []
    for y in range(top, top + rows):
        v = 0
        for x in range(cell_w):
            if px[cell_w + x, y]:
                v |= 1 << (cell_w - 1 - x)
        out.append(v)
    return out


def generate():
    lines = [
        "// GENERATED by cart/tools/mkwebfonts.py. Do not edit.",
        "// Both fonts are by GGBotNet and dedicated to the public domain (CC0 1.0).",
        "",
        'import type { BitmapFont } from "./text.ts";',
        "",
    ]
    for const, name, url, ttf, size, cell_w, top, rows in FONTS:
        font = ImageFont.truetype(os.path.join(CART, "assets", "font", *ttf), size)
        advances = {font.getlength(chr(c)) for c in range(FIRST, LAST + 1)}
        if advances != {float(cell_w)}:
            sys.exit(f"{name}: expected a monospaced {cell_w} px advance")
        lines.append(f"/** {name}, {url}: {cell_w} px cells, {rows} rows. */")
        lines.append(f"export const {const}: BitmapFont = {{")
        lines.append(f"  cellW: {cell_w},")
        lines.append(f"  rows: {rows},")
        lines.append(f"  first: {FIRST},")
        lines.append(f"  last: {LAST},")
        lines.append("  glyphs: new Uint16Array([")
        for code in range(FIRST, LAST + 1):
            vals = ", ".join(f"0x{v:03x}" for v in glyph_rows(font, size, cell_w, top, rows, chr(code), name))
            lines.append(f"    {vals}, // 0x{code:02x}")
        lines.append("  ]),")
        lines.append("};")
        lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = generate()
    if args.check:
        with open(OUT, encoding="ascii", newline="") as f:
            if f.read() != text:
                sys.exit(f"{OUT} is out of date; run cart/tools/mkwebfonts.py")
        print("web font tables are current")
        return
    with open(OUT, "w", encoding="ascii", newline="\n") as f:
        f.write(text)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
